language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'

cache:
  pip: true
  directories:
  - eggs/

install:
  - python bootstrap.py
  - bin/buildout -c buildout-test.cfg

script: bin/test

notifications:
  email:
    on_success: change
    on_failure: always
