---
dist: trusty
sudo: false

language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'

cache:
  pip: true
  directories:
  - eggs/

before_install:
  - pip install --upgrade pip

install:
  - pip --version
  - python bootstrap.py
  - bin/buildout

script: bin/test

notifications:
  email:
    on_success: change
    on_failure: always
